# Generated by Django 2.2.5 on 2019-09-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extras',
        ),
        migrations.AddField(
            model_name='student',
            name='co_curr',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_curr',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
