# Generated by Django 2.2.5 on 2019-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190927_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='internal1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='internal2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='internal3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='internal4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='internal5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='internal6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_name1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_name2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_name3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_name4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_name5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_name6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='theory1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='theory2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='theory3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='theory4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='theory5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='theory6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total6',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
